// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220404123520_1st")]
    partial class _1st
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "2fe43c9e-d0c6-4f67-baa4-c99a299961b4",
                            Email = "em@mail.com",
                            EmailConfirmed = true,
                            FirstName = "Emssi",
                            LastName = "House",
                            LockoutEnabled = false,
                            NormalizedEmail = "EM@MAIL.COM",
                            NormalizedUserName = "EMHOUSE",
                            PasswordHash = "AQAAAAEAACcQAAAAELRE2U++Gy5tpt14HJwPYhq9ajSivlhSG5GcswQBL8VJYksLvlAQ+usbRS0U9/ro8Q==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "emhouse"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            CompanyId = 3,
                            ConcurrencyStamp = "1b915ffa-abad-4634-adaa-2846ffbeb45c",
                            Email = "bella@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Bella",
                            LastName = "House",
                            LockoutEnabled = false,
                            NormalizedEmail = "BELLA@MAIL.COM",
                            NormalizedUserName = "BELLA@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEC+YnvFVuxAmKqAGR/LKegAk6oTQxT/FNmFLcnl/rajMs3nsKMMIP6SwyF+iQ4RzqA==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bella@mail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "13e37366-853b-4c5c-b2e0-863749e17c10",
                            Email = "b@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Basic",
                            LastName = "House",
                            LockoutEnabled = false,
                            NormalizedEmail = "B@MAIL.COM",
                            NormalizedUserName = "B@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJpzhO5NAlfyi/JvDdn1Pob6nRD1Z7bgx9s98Zreq6kQHG6D2/2tABfAovtIxd/cRw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "b@mail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "deb770e8-9965-421e-adb7-e27663716c5b",
                            Email = "emma@mail.com",
                            EmailConfirmed = true,
                            FirstName = "Emma",
                            LastName = "House",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA@MAIL.COM",
                            NormalizedUserName = "EMMAH",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "emmah"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bruw Brey"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Allissons CO"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bellaroom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dreeble"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Emelie style"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jesus Bak & Slakt AB"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Fitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StyleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.ToTable("Fittings");
                });

            modelBuilder.Entity("Domain.Entities.Grading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MeasurementPointId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementPointId");

                    b.HasIndex("SizeId");

                    b.ToTable("Gradings");
                });

            modelBuilder.Entity("Domain.Entities.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentMeasurementId")
                        .HasColumnType("int");

                    b.Property<int?>("StyleId")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentMeasurementId");

                    b.HasIndex("StyleId");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1st",
                            StyleId = 1,
                            UnitOfMeasure = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "2nd",
                            StyleId = 1,
                            UnitOfMeasure = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "3d",
                            StyleId = 1,
                            UnitOfMeasure = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "1st",
                            ParentMeasurementId = 3,
                            StyleId = 2,
                            UnitOfMeasure = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "1st",
                            StyleId = 3,
                            UnitOfMeasure = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "1st",
                            StyleId = 4,
                            UnitOfMeasure = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "2nd",
                            StyleId = 4,
                            UnitOfMeasure = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.MeasurementPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<float?>("Tolerance")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("MeasurementPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "½ chest",
                            MeasurementId = 1,
                            ShortName = "A",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 2,
                            Description = "½ waist",
                            MeasurementId = 1,
                            ShortName = "B",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 3,
                            Description = "½ hip",
                            MeasurementId = 1,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 4,
                            Description = "Front length from HPS",
                            MeasurementId = 1,
                            ShortName = "D",
                            Tolerance = 1f
                        },
                        new
                        {
                            Id = 5,
                            Description = "Neck width",
                            MeasurementId = 1,
                            ShortName = "E",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 6,
                            Description = "Neck drop front",
                            MeasurementId = 1,
                            ShortName = "F",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 7,
                            Description = "Neck drop back",
                            MeasurementId = 1,
                            ShortName = "G",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 8,
                            Description = "Across shoulder",
                            MeasurementId = 1,
                            ShortName = "H",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sleeve length from CB",
                            MeasurementId = 1,
                            ShortName = "I",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 10,
                            Description = "½ upper sleeve with",
                            MeasurementId = 1,
                            ShortName = "J",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 11,
                            Description = "½ sleeve opening",
                            MeasurementId = 1,
                            ShortName = "K",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 12,
                            Description = "Neck rib height",
                            MeasurementId = 1,
                            ShortName = "L",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 13,
                            Description = "Pocket width",
                            MeasurementId = 1,
                            ShortName = "M1",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 14,
                            Description = "Pocket height",
                            MeasurementId = 1,
                            ShortName = "M2",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 15,
                            Description = "Pocket from CF neck",
                            MeasurementId = 1,
                            ShortName = "M3",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 16,
                            Description = "½ chest",
                            MeasurementId = 2,
                            ShortName = "A",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 17,
                            Description = "½ waist",
                            MeasurementId = 2,
                            ShortName = "B",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 18,
                            Description = "½ hip",
                            MeasurementId = 2,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 19,
                            Description = "Front length from HPS",
                            MeasurementId = 2,
                            ShortName = "D",
                            Tolerance = 1f
                        },
                        new
                        {
                            Id = 20,
                            Description = "Neck width",
                            MeasurementId = 2,
                            ShortName = "E",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 21,
                            Description = "Neck drop front",
                            MeasurementId = 2,
                            ShortName = "F",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 22,
                            Description = "Neck drop back",
                            MeasurementId = 2,
                            ShortName = "G",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 23,
                            Description = "Across shoulder",
                            MeasurementId = 2,
                            ShortName = "H",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 24,
                            Description = "Sleeve length from CB",
                            MeasurementId = 2,
                            ShortName = "I",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 25,
                            Description = "½ upper sleeve with",
                            MeasurementId = 2,
                            ShortName = "J",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 26,
                            Description = "½ sleeve opening",
                            MeasurementId = 2,
                            ShortName = "K",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 27,
                            Description = "Neck rib height",
                            MeasurementId = 2,
                            ShortName = "L",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 28,
                            Description = "Pocket width",
                            MeasurementId = 2,
                            ShortName = "M1",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 29,
                            Description = "Pocket height",
                            MeasurementId = 2,
                            ShortName = "M2",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 30,
                            Description = "Pocket placement from HPS",
                            MeasurementId = 2,
                            ShortName = "M3",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 31,
                            Description = "½ chest",
                            MeasurementId = 3,
                            ShortName = "A",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 32,
                            Description = "½ waist",
                            MeasurementId = 3,
                            ShortName = "B",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 33,
                            Description = "½ hip",
                            MeasurementId = 3,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 34,
                            Description = "Front length from HPS",
                            MeasurementId = 3,
                            ShortName = "D",
                            Tolerance = 1f
                        },
                        new
                        {
                            Id = 35,
                            Description = "Neck width",
                            MeasurementId = 3,
                            ShortName = "E",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 36,
                            Description = "Neck drop front",
                            MeasurementId = 3,
                            ShortName = "F",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 37,
                            Description = "Neck drop back",
                            MeasurementId = 3,
                            ShortName = "G",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 38,
                            Description = "Across shoulder",
                            MeasurementId = 3,
                            ShortName = "H",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 39,
                            Description = "Sleeve length from CB",
                            MeasurementId = 3,
                            ShortName = "I",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 40,
                            Description = "½ upper sleeve with",
                            MeasurementId = 3,
                            ShortName = "J",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 41,
                            Description = "½ sleeve opening",
                            MeasurementId = 3,
                            ShortName = "K",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 42,
                            Description = "Neck rib height",
                            MeasurementId = 3,
                            ShortName = "L",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 43,
                            Description = "Pocket width",
                            MeasurementId = 3,
                            ShortName = "M1",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 44,
                            Description = "Pocket height",
                            MeasurementId = 3,
                            ShortName = "M2",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 45,
                            Description = "Pocket placement from HPS",
                            MeasurementId = 3,
                            ShortName = "M3",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 83,
                            Description = "Shoulderslope",
                            MeasurementId = 3,
                            ShortName = "1",
                            Tolerance = 0.2f
                        },
                        new
                        {
                            Id = 46,
                            Description = "½ chest",
                            MeasurementId = 4,
                            ShortName = "A",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 47,
                            Description = "½ waist",
                            MeasurementId = 4,
                            ShortName = "B",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 48,
                            Description = "½ hip",
                            MeasurementId = 4,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 49,
                            Description = "Front length from HPS",
                            MeasurementId = 4,
                            ShortName = "D",
                            Tolerance = 1f
                        },
                        new
                        {
                            Id = 50,
                            Description = "Neck width",
                            MeasurementId = 4,
                            ShortName = "E",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 51,
                            Description = "Neck drop front",
                            MeasurementId = 4,
                            ShortName = "F",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 52,
                            Description = "Neck drop back",
                            MeasurementId = 4,
                            ShortName = "G",
                            Tolerance = 0.25f
                        },
                        new
                        {
                            Id = 53,
                            Description = "Shoulder width",
                            MeasurementId = 4,
                            ShortName = "H",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 54,
                            Description = "Sleeve length from CB",
                            MeasurementId = 4,
                            ShortName = "I",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 55,
                            Description = "½ upper sleeve with",
                            MeasurementId = 4,
                            ShortName = "J",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 56,
                            Description = "½ sleeve opening",
                            MeasurementId = 4,
                            ShortName = "K",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 57,
                            Description = "Neck rib height",
                            MeasurementId = 4,
                            ShortName = "L",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 58,
                            Description = "Print width",
                            MeasurementId = 4,
                            ShortName = "M1",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 59,
                            Description = "Print height",
                            MeasurementId = 4,
                            ShortName = "M2",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 60,
                            Description = "Print placement from HPS",
                            MeasurementId = 4,
                            ShortName = "M3",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 84,
                            Description = "Shoulderslope",
                            MeasurementId = 4,
                            ShortName = "1",
                            Tolerance = 0.2f
                        },
                        new
                        {
                            Id = 61,
                            Description = "½ waist, relaxed",
                            MeasurementId = 5,
                            ShortName = "A1",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 62,
                            Description = "½ waist, extended",
                            MeasurementId = 5,
                            ShortName = "A2"
                        },
                        new
                        {
                            Id = 63,
                            Description = "½ waist, at seam",
                            MeasurementId = 5,
                            ShortName = "A3",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 64,
                            Description = "Waistband height",
                            MeasurementId = 5,
                            ShortName = "A4",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 88,
                            Description = "String length at waist",
                            MeasurementId = 5,
                            ShortName = "A5",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 65,
                            Description = "½ hip, 8cm from waist seam at CF",
                            MeasurementId = 5,
                            ShortName = "B",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 66,
                            Description = "½ thigh",
                            MeasurementId = 5,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 85,
                            Description = "½ knee, at ½ inseam",
                            MeasurementId = 5,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 86,
                            Description = "½ leg opening,5cm above seam",
                            MeasurementId = 5,
                            ShortName = "D1",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 87,
                            Description = "½ leg opening",
                            MeasurementId = 5,
                            ShortName = "D2",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 67,
                            Description = "mudd height",
                            MeasurementId = 5,
                            ShortName = "D3",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 68,
                            Description = "CF length",
                            MeasurementId = 5,
                            ShortName = "E",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 69,
                            Description = "Cb length",
                            MeasurementId = 5,
                            ShortName = "F",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 70,
                            Description = "Inseam length",
                            MeasurementId = 5,
                            ShortName = "G",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 71,
                            Description = "Cup height",
                            MeasurementId = 6,
                            ShortName = "A",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 72,
                            Description = "Cup width, at bottom",
                            MeasurementId = 6,
                            ShortName = "B1",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 73,
                            Description = "Cup width, at ½ height",
                            MeasurementId = 6,
                            ShortName = "B2",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 74,
                            Description = "String length, at neck",
                            MeasurementId = 6,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 75,
                            Description = "String length, at waist",
                            MeasurementId = 6,
                            ShortName = "D",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 76,
                            Description = "Cup height",
                            MeasurementId = 6,
                            ShortName = "A",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 77,
                            Description = "Cup width, at bottom",
                            MeasurementId = 6,
                            ShortName = "B1",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 78,
                            Description = "Cup width, at ½ height",
                            MeasurementId = 6,
                            ShortName = "B2",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 79,
                            Description = "String length, at neck",
                            MeasurementId = 6,
                            ShortName = "C",
                            Tolerance = 0.5f
                        },
                        new
                        {
                            Id = 80,
                            Description = "String length, at waist",
                            MeasurementId = 6,
                            ShortName = "D",
                            Tolerance = 2f
                        },
                        new
                        {
                            Id = 81,
                            Description = "Print width",
                            MeasurementId = 6,
                            ShortName = "1",
                            Tolerance = 0.3f
                        },
                        new
                        {
                            Id = 82,
                            Description = "Print placement from seam",
                            MeasurementId = 6,
                            ShortName = "2",
                            Tolerance = 0.3f
                        });
                });

            modelBuilder.Entity("Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderdIndex")
                        .HasColumnType("int");

                    b.Property<int>("SizeRangeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SizeRangeId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XS",
                            OrderdIndex = 1,
                            SizeRangeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "S",
                            OrderdIndex = 2,
                            SizeRangeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "M",
                            OrderdIndex = 3,
                            SizeRangeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "L",
                            OrderdIndex = 4,
                            SizeRangeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "XL",
                            OrderdIndex = 5,
                            SizeRangeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "XS",
                            OrderdIndex = 1,
                            SizeRangeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "S",
                            OrderdIndex = 2,
                            SizeRangeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "M",
                            OrderdIndex = 3,
                            SizeRangeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "L",
                            OrderdIndex = 4,
                            SizeRangeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "XL",
                            OrderdIndex = 5,
                            SizeRangeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "XS",
                            OrderdIndex = 1,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "S",
                            OrderdIndex = 2,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "M",
                            OrderdIndex = 3,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "L",
                            OrderdIndex = 4,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "XL",
                            OrderdIndex = 5,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "XS",
                            OrderdIndex = 1,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "S",
                            OrderdIndex = 2,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "M",
                            OrderdIndex = 3,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "L",
                            OrderdIndex = 4,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "XL",
                            OrderdIndex = 5,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "34",
                            OrderdIndex = 1,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "36",
                            OrderdIndex = 2,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "38",
                            OrderdIndex = 3,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "40",
                            OrderdIndex = 4,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "42",
                            OrderdIndex = 5,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 26,
                            Name = "44",
                            OrderdIndex = 6,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "34",
                            OrderdIndex = 1,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "36",
                            OrderdIndex = 2,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "38",
                            OrderdIndex = 3,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Name = "40",
                            OrderdIndex = 4,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "42",
                            OrderdIndex = 5,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "44",
                            OrderdIndex = 6,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 33,
                            Name = "34",
                            OrderdIndex = 1,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Name = "36",
                            OrderdIndex = 2,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 35,
                            Name = "38",
                            OrderdIndex = 3,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 36,
                            Name = "40",
                            OrderdIndex = 4,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 37,
                            Name = "42",
                            OrderdIndex = 5,
                            SizeRangeId = 3
                        },
                        new
                        {
                            Id = 38,
                            Name = "44",
                            OrderdIndex = 6,
                            SizeRangeId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.SizeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BaseSizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId")
                        .IsUnique();

                    b.ToTable("SizeRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSizeName = "M",
                            MeasurementId = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseSizeName = "M",
                            MeasurementId = 2
                        },
                        new
                        {
                            Id = 3,
                            BaseSizeName = "M",
                            MeasurementId = 3
                        },
                        new
                        {
                            Id = 4,
                            BaseSizeName = "M",
                            MeasurementId = 4
                        },
                        new
                        {
                            Id = 5,
                            BaseSizeName = "36",
                            MeasurementId = 5
                        },
                        new
                        {
                            Id = 6,
                            BaseSizeName = "38",
                            MeasurementId = 6
                        },
                        new
                        {
                            Id = 7,
                            BaseSizeName = "38",
                            MeasurementId = 7
                        });
                });

            modelBuilder.Entity("Domain.Entities.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Classic trouser with low wist and staight leg.",
                            Name = "Tshirt Smile",
                            OrderNumber = "lkj76aa4-12",
                            ProductGroup = "Women top",
                            ProductType = "Tricot",
                            StyleNumber = "a0",
                            Tags = "t-shirt,chestpocket,off-shoulder"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lose fitted long sleeve shirt with tilored fitt at waist. Print at center front chest.",
                            Name = "Lounge shirt",
                            OrderNumber = "aaqs21",
                            ProductGroup = "High fashion",
                            ProductType = "Tricot",
                            StyleNumber = "a1",
                            Tags = "chestprint,figure,long-sleeve"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Seamless yoga pants in elastic organic cotton mixed with elastane. High waist and pocket on left thigh.",
                            Name = "Yoga tights",
                            OrderNumber = "123abc",
                            ProductGroup = "Women Sport",
                            ProductType = "Training",
                            StyleNumber = "a2",
                            Tags = "compress,lycra"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToUserId = 1,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Vivvi",
                            OrderNumber = "AW22-981",
                            ProductGroup = "Underwear",
                            ProductType = "Bikini top",
                            StyleNumber = "a3",
                            Tags = "mockfabric,brazilian"
                        },
                        new
                        {
                            Id = 5,
                            AssignedToUserId = 1,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Annz",
                            OrderNumber = "AW22-982",
                            ProductGroup = "Underwear",
                            ProductType = "Bikini top",
                            StyleNumber = "a4",
                            Tags = "mockfabric,triangle,fashion"
                        },
                        new
                        {
                            Id = 6,
                            AssignedToUserId = 1,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Vivvi",
                            OrderNumber = "AW22-983",
                            ProductGroup = "Underwear",
                            ProductType = "Bikini bottom",
                            StyleNumber = "a5",
                            Tags = "highwaist,wideside,compression"
                        },
                        new
                        {
                            Id = 7,
                            AssignedToUserId = 1,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Annz",
                            OrderNumber = "AW22-984",
                            ProductGroup = "Underwear",
                            ProductType = "Bikini bottom",
                            StyleNumber = "a6",
                            Tags = "regularFitt,noseams"
                        },
                        new
                        {
                            Id = 8,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Elsa swim",
                            OrderNumber = "AW22-985",
                            ProductGroup = "Underwear",
                            ProductType = "Swimsuit child",
                            StyleNumber = "a7",
                            Tags = "skirt,crossback"
                        },
                        new
                        {
                            Id = 9,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Elva yos",
                            OrderNumber = "AW22-986",
                            ProductGroup = "Sport",
                            ProductType = "Yoga pants",
                            StyleNumber = "a8",
                            Tags = "looseleg,wideleg,highwaist,foldedwaistband"
                        },
                        new
                        {
                            Id = 10,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Elva pas",
                            OrderNumber = "AW22-987",
                            ProductGroup = "Sport",
                            ProductType = "Yoga pants",
                            StyleNumber = "a9",
                            Tags = "straightleg,highwaist,7/8-length"
                        },
                        new
                        {
                            Id = 11,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Pas esma",
                            OrderNumber = "AW22-988",
                            ProductGroup = "Sport",
                            ProductType = "Yoga top",
                            StyleNumber = "b1",
                            Tags = "loosefitt,tshirt,openback"
                        },
                        new
                        {
                            Id = 12,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Seamless Ribb Tights",
                            OrderNumber = "AW22-989",
                            ProductGroup = "Sport",
                            ProductType = "Tights",
                            StyleNumber = "b2",
                            Tags = "compression,legpocket,7/8-length"
                        },
                        new
                        {
                            Id = 13,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Fancyann Tights",
                            OrderNumber = "AW22-921",
                            ProductGroup = "Sport",
                            ProductType = "Tights",
                            StyleNumber = "b3",
                            Tags = "thinfabric,waistpocket,full-length"
                        },
                        new
                        {
                            Id = 14,
                            AssignedToUserId = 3,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Seamless Anna Top",
                            OrderNumber = "AW22-922",
                            ProductGroup = "Sport",
                            ProductType = "Bra",
                            StyleNumber = "b4",
                            Tags = "crossback,keypocket,padding"
                        },
                        new
                        {
                            Id = 15,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Lova Top",
                            OrderNumber = "AW22-923",
                            ProductGroup = "Sport",
                            ProductType = "Bra",
                            StyleNumber = "b5",
                            Tags = "compression,nopadding,v-ring"
                        },
                        new
                        {
                            Id = 16,
                            AssignedToUserId = 3,
                            CompanyId = 1,
                            Description = "Lose fitted bluse in shire vowen satin with voulumos sleev with elastic mudd.",
                            Name = "Lovalia",
                            OrderNumber = "AW22-924",
                            ProductGroup = "Tricot",
                            ProductType = "Long dress",
                            StyleNumber = "b6",
                            Tags = "volumeskirt,strassfeeling,summerdress"
                        },
                        new
                        {
                            Id = 17,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Jhonna printed dress",
                            OrderNumber = "AW22-925",
                            ProductGroup = "Tricot",
                            ProductType = "Short dress",
                            StyleNumber = "b7",
                            Tags = "classic,tailoredfitt,elastic"
                        },
                        new
                        {
                            Id = 18,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Alva ",
                            OrderNumber = "AW22-926",
                            ProductGroup = "Tricot",
                            ProductType = "Pants",
                            StyleNumber = "b8",
                            Tags = "classic,tailoredfitt,elastic"
                        },
                        new
                        {
                            Id = 19,
                            AssignedToUserId = 3,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Alva ankle length",
                            OrderNumber = "AW22-927",
                            ProductGroup = "Tricot",
                            ProductType = "Pants",
                            StyleNumber = "b9",
                            Tags = "7/8-length,elasticwaist,nice"
                        },
                        new
                        {
                            Id = 20,
                            AssignedToUserId = 4,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Flica Basic T-shirt",
                            OrderNumber = "AW22-928",
                            ProductGroup = "Tricot",
                            ProductType = "T-shirt",
                            StyleNumber = "c1",
                            Tags = "highfashion,spring32,londonCollection,colab-joss"
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Flica Basic Blouse",
                            OrderNumber = "AW22-929",
                            ProductGroup = "Light vowen",
                            ProductType = "Blouse",
                            StyleNumber = "c2",
                            Tags = "colab-joss,premium,classic"
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 1,
                            Description = "Lorem ipsum hapsum di ab sa nog live av list mos dent italid flori data min gonsedl moli.",
                            Name = "Nna Shirt",
                            OrderNumber = "AW22-871",
                            ProductGroup = "Light vowen",
                            ProductType = "Shirt",
                            StyleNumber = "c3",
                            Tags = "colab-elsa,premium,classic"
                        },
                        new
                        {
                            Id = 23,
                            AssignedToUserId = 2,
                            CompanyId = 3,
                            Description = "Denna tillhör företag 3 och ska endast synas på dennes användares inlogg! :).",
                            Name = "Yoga",
                            OrderNumber = "AW22-872",
                            ProductGroup = "Light vowen",
                            ProductType = "Blouse",
                            StyleNumber = "c4",
                            Tags = "colab-elsa,premium,classic"
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 3,
                            Description = "Lorem lipsum comapny 3 here",
                            Name = "Yoga no.3",
                            OrderNumber = "AW22-873",
                            ProductGroup = "Yoga",
                            ProductType = "Pants women",
                            StyleNumber = "c5",
                            Tags = "colab-elsa,premium,classic"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Fitting", b =>
                {
                    b.HasOne("Domain.Entities.Style", "Style")
                        .WithMany("Fittings")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");
                });

            modelBuilder.Entity("Domain.Entities.Grading", b =>
                {
                    b.HasOne("Domain.Entities.MeasurementPoint", "MeasurementPoint")
                        .WithMany()
                        .HasForeignKey("MeasurementPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementPoint");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Domain.Entities.Measurement", b =>
                {
                    b.HasOne("Domain.Entities.Measurement", "ParentMeasurement")
                        .WithMany()
                        .HasForeignKey("ParentMeasurementId");

                    b.HasOne("Domain.Entities.Style", "Style")
                        .WithMany("Measurements")
                        .HasForeignKey("StyleId");

                    b.Navigation("ParentMeasurement");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("Domain.Entities.MeasurementPoint", b =>
                {
                    b.HasOne("Domain.Entities.Measurement", "Measurement")
                        .WithMany("MeasurementPoints")
                        .HasForeignKey("MeasurementId");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Domain.Entities.Size", b =>
                {
                    b.HasOne("Domain.Entities.SizeRange", "SizeRange")
                        .WithMany("Sizes")
                        .HasForeignKey("SizeRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SizeRange");
                });

            modelBuilder.Entity("Domain.Entities.SizeRange", b =>
                {
                    b.HasOne("Domain.Entities.Measurement", "Measurement")
                        .WithOne("SizeRange")
                        .HasForeignKey("Domain.Entities.SizeRange", "MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Domain.Entities.Style", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany("Styles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Navigation("Styles");
                });

            modelBuilder.Entity("Domain.Entities.Measurement", b =>
                {
                    b.Navigation("MeasurementPoints");

                    b.Navigation("SizeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.SizeRange", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Domain.Entities.Style", b =>
                {
                    b.Navigation("Fittings");

                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
